---
# tasks file for rancher

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: true
  ignore_errors: true
  tags:
    - server
    - worker

- name: determine if we're already running an agent
  shell: "docker ps | fgrep -q rancher/agent"
  register: agent_installed
  ignore_errors: true
  changed_when: false
  become: true
  when: ansible_hostname == '26a-rancher-0'
  tags:
    - server

- name: Start the Rancher server
  become: true
  shell: "docker run -dit --name {{ ansible_hostname }} --restart unless-stopped -p 80:8080 -v /opt:/var/lib/mysql rancher/server:v1.6.25"
  ignore_errors: true
  when: not agent_installed|success and ansible_hostname == '26a-rancher-0'
  tags:
    - server

- name: install jq
  become: true
  yum:
    name: jq
    state: installed
  ignore_errors: true
  tags:
    - worker

- name: wait for rancher server is up and running
  become: true
  wait_for:
    host: "{{ hostvars['26a-rancher-0'].ansible_default_ipv4.address }}"
    port: "80"
  ignore_errors: true
  when: ansible_hostname == '26a-rancher-0'
  tags:
    - check

- name: Get Project Info
  become: true
  shell: "curl http://{{ hostvars['26a-rancher-0'].ansible_default_ipv4.address }}/v2-beta/projects/ | jq -r '.data[].id'"
  register: rancher_server_project
  ignore_errors: true
  when: ansible_hostname != '26a-rancher-0'
  tags:
    - worker

- name: Get ResgistrationTokenId
  become: true
  shell: "curl -X POST -H 'Accept: application/json' http://{{ hostvars['26a-rancher-0'].ansible_default_ipv4.address }}/v2-beta/projects/{{ rancher_server_project.stdout }}/registrationtokens | jq -r '.links.self'"
  register: register_tokenid
  ignore_errors: true
  when: ansible_hostname != '26a-rancher-0'
  tags:
    - worker

- name: Get RegistrationURL
  become: true
  shell: "curl -X GET -H 'Accept: application/json' {{ register_tokenid.stdout }} | jq -r '.command'"
  register: registration_url
  ignore_errors: true
  when: ansible_hostname != '26a-rancher-0'
  tags:
    - worker

- name: Launch Rancher workers
  become: true
  shell: "{{ registration_url.stdout }} "
  ignore_errors: true
  when: ansible_hostname != '26a-rancher-0'
  tags:
    - worker