---
# handlers file for docker
- name: docker start
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

- name: docker stop
  become: true
  systemd:
    name: docker
    state: stopped

- name: docker restart
  become: true
  systemd:
    name: docker
    state: restarted
    daemon_reload: true