---
# tasks file for docker

- name: determine if docker is installed
  become: true
  shell: which docker
  register: docker_present
  ignore_errors: true
  changed_when: false

- name: determine if pip is present
  become: true
  shell: which pip
  register: pip_present
  ignore_errors: true
  changed_when: false

- name: Install Prerequisites
  become: true
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: true
  ignore_errors: true
  when: not docker_present|success
  with_items:
    - epel-release
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Install Python and Pip
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: true
  ignore_errors: true
  when: not pip_present|success
  with_items:
    - python-pip
    - python

- name: Add Docker repository
  become: true
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  ignore_errors: true
  when: not docker_present|success

- name: Install Docker
  become: true
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  ignore_errors: true
  when: not docker_present|success
  notify: docker start

- name: install docker-py
  become: true
  pip:
    name: docker-py

- name: docker login to docker hub
  become: true
  docker_login:
    password: "{{ docker_pass }}"
    username: "{{ docker_login }}"
